tunnel: 75633391-cc4c-4bd4-bea3-53780d8ccd43
credentials-file: C:\Users\Mafius\.cloudflared\75633391-cc4c-4bd4-bea3-53780d8ccd43.json

ingress:
  # Route all traffic from letstestit.me to Caddy reverse proxy
  # Caddy handles both static files and API routing (/api/*)
  - hostname: letstestit.me
    service: http://localhost:80
  # Fallback for any other requests
  - service: http_status:404
